language: node_js
cache: npm
stages:
  - check
  - test

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx

script: npm run test

jobs:
  include:
    - stage: check
      script:
        - npx aegir commitlint --travis
        - npx aegir dep-check
        - npm run lint

notifications:
  email: false
